server:
  port: 8888

spring:
  application:
    name: go_phone
  datasource:
    url: ${DB_URL}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  security:
    filter:
      dispatcher-types: REQUEST,ASYNC,ERROR
  jwt:
    secret: ${JWT_SECRET}
    access-token-exp: ${ACCESS-TOKEN-EXP}
    refresh-token-exp: ${REFRESH-TOKEN-EXP}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
    ping:
      enabled: true
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

mybatis:
  config-location: classpath:mybatis/configuration/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/**/*.xml