server:
  port: 8888

spring:
  application:
    name: go_phone
  datasource:
    url: ${DB_URL}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

mybatis:
  config-location: classpath:mybatis/configuration/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/**/*.xml