server:
  port: 8888

#debug: true

spring:
  application:
    name: go_phone
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000
  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:}
    password: ${SMTP_PASSWORD:}
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000

mail:
  from:
    email: ${MAIL_FROM_EMAIL:${SMTP_USERNAME}}
    name: ${MAIL_FROM_NAME:Go Phone}

app:
  name: ${APP_NAME:Go Phone}
  base-url: ${APP_BASE_URL:http://localhost:8888}
  otp:
    ttl-seconds: ${OTP_TTL_SECONDS:300}
    resend-window-seconds: ${OTP_RESEND_WINDOW_SECONDS:60}
    max-attempts: ${OTP_MAX_ATTEMPTS:5}
  payment:
    return-path: /payos/return
    webhook-path: /api/webhooks/payos

jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER}
  access-exp-minutes: ${JWT_ACCESS_EXP_MINUTES}

payos:
  client-id: ${PAYOS_CLIENT_ID}
  api-key: ${PAYOS_API_KEY}
  checksum-key: ${PAYOS_CHECKSUM_KEY}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
    ping:
      enabled: true
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

mybatis:
  config-location: classpath:mybatis/configuration/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/**/*.xml