name: GoPhone

on:
  workflow_dispatch:
  pull_request:
    types: [ closed ]
    branches: [ main ]
    paths:
      - 'src/**'
      - '.github/workflows/go-phone-workflow.yml'

env:
  IMAGE_NAME: "${{ secrets.DOCKERHUB_USERNAME }}/gophone-backend"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./ 
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
